services:
  mapserver:
    image: it.enboso.com:8080/wm/tileserver-gl:latest
    container_name: tileserver
    ports:
      - 8081:8080
    volumes:
      - ./data/tileserver:/data
    networks:
      - internal-network

networks:
  internal-network:
    external: true
    name: internal-br
